//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bristlecone.Auth.Identity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bristlecone.Auth.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} already deleted:{1}.
        /// </summary>
        internal static string BristleconeEmployeeUserStore_DeleteAsync_Employee__0__already_deleted__1_ {
            get {
                return ResourceManager.GetString("BristleconeEmployeeUserStore_DeleteAsync_Employee__0__already_deleted__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A participant needs to be added to the account..
        /// </summary>
        internal static string BristleconeParticipantUserStore_CreateAsync_A_participant_needs_to_be_added_to_the_account_ {
            get {
                return ResourceManager.GetString("BristleconeParticipantUserStore_CreateAsync_A_participant_needs_to_be_added_to_the_accoun" +
                        "t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant with ID {0} already deleted:{1}.
        /// </summary>
        internal static string BristleconeParticipantUserStore_DeleteAsync_Participant_with_ID__0__already_deleted__1_ {
            get {
                return ResourceManager.GetString("BristleconeParticipantUserStore_DeleteAsync_Participant_with_ID__0__already_deleted__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An employee needs to be added to the account..
        /// </summary>
        internal static string MissingEmployeeException {
            get {
                return ResourceManager.GetString("MissingEmployeeException", resourceCulture);
            }
        }
    }
}
